WebApplication1/Areas/ModulAdmin/ViewModels/Dolasci/DolasciDodajVM.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Dolasci
{
    public class DolasciDodajVM
    {
        public int Id { get; set; }

        [BindRequired]
        public int ZaposlenikId { get; set; }
        public List<SelectListItem> ZaposleniciList { get; set; }
    }
}

WebApplication1/Areas/ModulAdmin/ViewModels/Dolasci/DolasciList.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Dolasci
{
    public class DolasciList
    {
        public List<Row> htmlRows { get; set; }
        public class Row
        {
            public int Id { get; set; }
            public string Zaposlenik { get; set; }
            public DateTime? Dolazak { get; set; }
            public DateTime? Odlazak { get; set; }
            public int? SatiRadili { get; set; }

        }
    }
}

WebApplication1/Models/Dolasci.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Dolasci
    {
        [Key]
        public int Id { get; set; }
        
        public int ZaposlenikId { get; set; }
        [ForeignKey("ZaposlenikId")]
        public Zaposlenik Zaposlenik { get; set; }


        public DateTime Dolazak { get; set; }
        public DateTime? Odlazak { get; set; }

        public int? SatiRadio { get; set; }

    }
}

WebApplication1/Areas/ModulAdmin/Controllers/DolasciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.Areas.ModulAdmin.ViewModels.Dolasci;
using WebApplication1.EF;
using WebApplication1.Models;
using WebApplication1.Helper;

namespace WebApplication1.Areas.ModulAdmin.Controllers
{
    [Autorizacija(zaposlenik: true, korisnik: false)]

    [Area("ModulAdmin")]
    [Route("/ModulAdmin/Dolasci")]
    public class DolasciController : Controller
    {
        private MyContext _db;
        public DolasciController(MyContext baza)
        {
            _db = baza;
        }


        [Route("/ModulAdmin/Dolasci/List")]
        public IActionResult List()
        {
            DolasciList model = new DolasciList
            {
                htmlRows = _db.Dolasci.Select(s => new DolasciList.Row
                {
                    Id = s.Id,
                    Dolazak = s.Dolazak,
                    Odlazak = s.Odlazak,
                    Zaposlenik = s.Zaposlenik.Ime + " " + s.Zaposlenik.Prezime,
                    SatiRadili = s.SatiRadio
                }).ToList()
            };
            return View(model);
        }

        [Route("/ModulAdmin/Dolasci/Dodaj")]
        public IActionResult Dodaj()
        {
            DolasciDodajVM model = new DolasciDodajVM();
            GenerisiCmbStavke(model);

            return View(model);
        }

        [Route("/ModulAdmin/Dolasci/Zavrsio")]
        public IActionResult Zavrsio(int id)
        {
            Dolasci d = _db.Dolasci.Find(id);

            DateTime sada = DateTime.Now;
            d.Odlazak = sada;
            d.SatiRadio = sada.Subtract(d.Dolazak).Hours;

            _db.SaveChanges();
            return RedirectToAction("List");
        }


        [Route("/ModulAdmin/Dolasci/DodajSave")]
        public IActionResult DodajSave(DolasciDodajVM model)
        {

            if (ModelState.IsValid)
            {
                Dolasci d = new Dolasci();
                _db.Add(d);
                
                d.SatiRadio = 0;
                d.Dolazak = DateTime.Now;
                d.Odlazak = null;
                d.ZaposlenikId = model.ZaposlenikId;
                _db.SaveChanges();


                return RedirectToAction("List");
            }
            else
            {
                GenerisiCmbStavke(model);
                return View("Dodaj", model);
            }
        }

        private void GenerisiCmbStavke(DolasciDodajVM model)
        {
            model.ZaposleniciList = _db.Zaposlenik.Select(s => new SelectListItem
            {
                Text = s.Ime + " " + s.Prezime,
                Value = s.Id.ToString()
            }).ToList();
        }
    }
}

WebApplication1/Controllers/DolasciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.EF;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class DolasciController : Controller
    {
        private MyContext db;
        public DolasciController(MyContext baza)
        {
            db = baza;
        }
        [HttpGet]
        public IActionResult Index()
        {
            ViewData["zaposlenik"] = db.Zaposlenik.ToList();

            ViewData["dolasci"] = db.Dolasci.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Index(int ZaposlenikID, DateTime Dolazak, DateTime Odlazak)
        {

            Dolasci j = new Dolasci();
            j.Dolazak = Dolazak;
            j.Odlazak = Odlazak;

            j.ZaposlenikId = ZaposlenikID;

            db.Dolasci.Add(j);
            db.SaveChanges();


            ViewData["zaposlenik"] = db.Zaposlenik.ToList();
            ViewData["dolasci"] = db.Dolasci.ToList();
            

            return View();
        }

        [HttpGet]
        public IActionResult Prikazi()
        {

            ViewData["zaposlenik"] = db.Zaposlenik.ToList();

            ViewData["dolasci"] = db.Dolasci.ToList();

            return View();
        }
    }
}

WebApplication1/Areas/ModulAdmin/Views/Dolasci/Dodaj.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Dolasci.DolasciDodajVM
@{
    ViewData["Title"] = "Dodaj";
}

<h2>Dodaj</h2>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Dodaj platu</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form asp-area="ModulAdmin" asp-controller="Dolasci" asp-action="DodajSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Zaposlenik">
                            Zaposlenik:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select asp-for="ZaposlenikId" asp-items="Model.ZaposleniciList" class="form-control">
                                <option value="" disabled hidden selected>(Odaberi zaposlenika)</option>
                            </select>
                            <span asp-validation-for="ZaposlenikId"></span>

                        </div>
                    </div>
                    
                    <input asp-for="Id" type="hidden" />

                    <div class="form-group">
                        <div class="col-md-9 text-right">
                            <button type="reset" class="btn btn-primary">Resetiraj</button>
                            <button type="submit" class="btn btn-success">Potvrdi</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WebApplication1/Areas/ModulAdmin/Views/Dolasci/List.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Dolasci.DolasciList
@{
    ViewData["Title"] = "Evidencija radnika";
    int br = 0;

}

<div class="row">
    <div class="x_panel">
        <div class="x_title">
            <h2>Evidencija radnika</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>RB</th>
                        <th>Ime i prezime</th>
                        <th>Dolazak</th>
                        <th>Odlazak</th>
                        <td>Sati radili</td>
                        <td>Akcija</td>
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var d in Model.htmlRows)
                        {
                            <tr>
                                @{
                                    br++;
                                }
                                <td>@br</td>
                                <td>@d.Zaposlenik</td>
                                <td>@d.Dolazak</td>
                                <td>@d.Odlazak</td>
                                <td>@d.SatiRadili</td>
                                <td class="text-center">
                                    @if (d.Odlazak == null)
                                    {

                                        <a asp-controller="Dolasci" asp-action="Zavrsio" asp-route-id="@d.Id" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>  Završio</a>
                                    }
                                </td>
                            </tr>
                        }
                    }
                </tbody>

            </table>
        </div>
        <a asp-controller="Dolasci" asp-action="Dodaj" class="btn btn-primary"> Dodaj novu evidenciju </a>
      
    </div>

</div>