WebApplication1/Areas/ModulAdmin/ViewModels/Rezervacija/RezervacijaDodajVM.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Rezervacija
{
    public class RezervacijaDodajVM
    {

        [Required(ErrorMessage = "Naziv događaja je obavezno polje")]
        [RegularExpression("^.{4,}$", ErrorMessage = "Događaj mora imat više od 4 slova")]
        public string Naziv { get; set; }

        public int RezervacijaId { get; set; }



      
        public int NarucilacId { get; set; }

        public int BrojStolova { get; set; }


        public string NarucilacIme { get; set; }
        public DateTime DatumEvidencije { get; set; }
        public DateTime DatumRezervacije { get; set; }
    }
}

WebApplication1/Areas/ModulAdmin/ViewModels/Rezervacija/RezervacijaFindGostVM.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Areas.ModulAdmin.Controllers;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Rezervacija
{
    public class RezervacijaFindGostVM
    {
        public List<Row> htmlRows { get; set; }
        public class Row
        {
            public string NarucilacId { get; set; }
            public string ImePrezime { get; set; }
            public string KorisnickoIme { get; set; }
            public string Email { get; set; }
            public string Telefon { get; set; }
            public string Adresa { get; set; }
            public string GradNaziv { get; set; }
        }
    }
}

WebApplication1/Areas/ModulAdmin/ViewModels/Rezervacija/RezervacijeListVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Rezervacija
{
    public class RezervacijeListVM
    {
        public List<Row> htmlRows { get; set; }
        public class Row
        {
            public int RezervacijaId { get; set; }
            public DateTime DatumEvidencije { get; set; }
            public DateTime DatumRezervacije { get; set; }
            public string Naziv { get; set; }
           
            public string ImePrezime { get; set; }

            public int BrojMjesta { get; set; }
        }
    }
}

WebApplication1/Areas/ModulAdmin/Controllers/RezervacijaController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.EF;
using WebApplication1.Models;
using WebApplication1.Areas.ModulAdmin.ViewModels.Rezervacija;
using WebApplication1.Helper;

namespace WebApplication1.Areas.ModulAdmin.Controllers
{
    [Autorizacija(zaposlenik: true, korisnik: false)]

    [Area("ModulAdmin")]
    [Route("/ModulAdmin/Rezervacija")]
    public class RezervacijaController : Controller
    {
        private MyContext db;
        public RezervacijaController(MyContext baza) { db = baza; }

        [Route("/ModulAdmin/Rezervacija/List")]
        public IActionResult List()
        {
            RezervacijeListVM model = new RezervacijeListVM
            {
                htmlRows = db.Rezervacija.Select(r => new RezervacijeListVM.Row()
                {
                    RezervacijaId = r.Id,
                    DatumEvidencije = r.DatumEvidencije,
                    DatumRezervacije = r.DatumRezervacije,
                    ImePrezime = r.Narucilac.ImePrezime,
                    Naziv = r.Naziv,
                    BrojMjesta = db.RezervacijaStavke.Where(w=> w.RezervacijaId == r.Id).Select(g => g.Stol.BrojMjesta).FirstOrDefault()
                }).ToList()
          };
          return View(model);
        }


        [Route("/ModulAdmin/Rezervacija/DodajGost")]
        public IActionResult DodajGost()
        {
            RezervacijaFindGostVM model = new RezervacijaFindGostVM
            {
                htmlRows = db.Narucilac.Select(n => new RezervacijaFindGostVM.Row
                {
                    NarucilacId = n.NarucilacId.ToString(),
                    ImePrezime = n.ImePrezime,
                    KorisnickoIme = n.KorisnickiNalog.KorisnickoIme,
                    Email = n.Email,
                    Telefon = n.Telefon,
                    Adresa = n.Adresa,
                    GradNaziv = n.Grad.Naziv
                }).ToList()
            };
            return View(model);  
        }

   

        [Route("/ModulAdmin/Rezervacija/Dodaj")]
        public IActionResult Dodaj(int id)
        {
            RezervacijaDodajVM model = new RezervacijaDodajVM();
         
            Narucilac n = db.Narucilac.Find(id);
            model.NarucilacId = id;
            model.NarucilacIme = n.ImePrezime;
            model.DatumEvidencije = DateTime.Now;
            return View(model);
        }


        [Route("/ModulAdmin/Rezervacija/Uredi")]
        [HttpGet]
        public IActionResult Uredi(int id)
        {
            Rezervacija rezervacija = db.Rezervacija.Find(id);
            RezervacijaStavke rs = db.RezervacijaStavke.Where(w => w.RezervacijaId == id).FirstOrDefault();
            Narucilac n = db.Narucilac.Where(w => w.NarucilacId == rezervacija.NarucilacId).FirstOrDefault();
            RezervacijaDodajVM model = new RezervacijaDodajVM();

            model.RezervacijaId = id;
            model.Naziv = rezervacija.Naziv;
            model.DatumEvidencije = rezervacija.DatumEvidencije;
            model.DatumRezervacije = rezervacija.DatumRezervacije;
            model.BrojStolova = rs.StolId;
            model.NarucilacIme = n.ImePrezime;
            model.NarucilacId = rezervacija.NarucilacId;
             

            return View(model);
        }

        [Route("/ModulAdmin/Rezervacija/Obrisi")]
        [HttpGet]
        public IActionResult Obrisi(int id)
        {
            Rezervacija obrisati = db.Rezervacija.SingleOrDefault(r => r.Id == id);
            IEnumerable<RezervacijaStavke> obrisatiStavke = db.RezervacijaStavke.Where(rs => rs.RezervacijaId == id);
            if (obrisati == null)
                return View("Error");

            foreach (RezervacijaStavke rezervacijaStavke in obrisatiStavke)
            {
                db.Remove(rezervacijaStavke);
            }
            db.Remove(obrisati);
            db.SaveChanges();

            return RedirectToAction("List");
        }
        [Route("/ModulAdmin/Rezervacija/DodajSave")]
        [HttpPost]
        public IActionResult DodajSave(RezervacijaDodajVM model)
        {
            if (ModelState.IsValid)
            {
                Rezervacija r = db.Rezervacija.Find(model.RezervacijaId);
                RezervacijaStavke rs = db.RezervacijaStavke.Where(w => w.RezervacijaId == model.RezervacijaId).FirstOrDefault();
                if (r == null)
                {
                    r = new Rezervacija();
                    rs = new RezervacijaStavke();
                    db.Add(r);
                    db.Add(rs);
                }


                r.NarucilacId = model.NarucilacId;
                r.Naziv = model.Naziv;
                r.DatumEvidencije = model.DatumEvidencije;
                r.DatumRezervacije = model.DatumRezervacije;

                rs.RezervacijaId = r.Id;
                rs.StolId = model.BrojStolova;

                db.SaveChanges();

                return RedirectToAction("List");
            }
            else
            {
             
                return View("Dodaj", model);
            }
    
        }

        [Route("/ModulAdmin/Rezervacija/UrediSave")]
        [HttpPost]
        public IActionResult UrediSave(RezervacijaDodajVM model)
        {
            if (ModelState.IsValid)
            {
                Rezervacija r = db.Rezervacija.Find(model.RezervacijaId);
                RezervacijaStavke rs = db.RezervacijaStavke.Where(w => w.RezervacijaId == model.RezervacijaId).FirstOrDefault();
                if (r == null)
                {
                    r = new Rezervacija();
                    rs = new RezervacijaStavke();
                    db.Add(r);
                    db.Add(rs);
                }


                r.NarucilacId = model.NarucilacId;
                r.Naziv = model.Naziv;
                r.DatumEvidencije = model.DatumEvidencije;
                r.DatumRezervacije = model.DatumRezervacije;

                rs.RezervacijaId = r.Id;
                rs.StolId = model.BrojStolova;

                db.SaveChanges();

                return RedirectToAction("List");
            }
            else
            {
                return View("Uredi", model);
            }

        }
    

      
     
    }
}

WebApplication1/Controllers/RezervacijaController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.EF;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class RezervacijaController : Controller
    {
        private MyContext db;
        public RezervacijaController(MyContext baza) { db = baza; }


        private RezervacijaDodajVM GenerisiCmbStavke()
        {
            return new RezervacijaDodajVM
            {
                stolLista = db.Stol.Select(x => new SelectListItem
                {
                    Text = x.Id.ToString(),
                    Value = x.Id.ToString()
                }).ToList(),
                narucilacLista = db.Narucilac.Select(n => new SelectListItem
                {
                    Text = n.ImePrezime,
                    Value = n.NarucilacId.ToString()
                }).ToList(),
            };
        }
     

        
        public IActionResult Prikazi()
        {
            RezervacijaPrikaziVM model = new RezervacijaPrikaziVM
            {

                htmlRows = db.RezervacijaStavke.Select(rs => new RezervacijaPrikaziVM.Row()
                {
                    Id = rs.RezervacijaId,
                    DatumEvidencije = DateTime.Now,
                    DatumRezervacije = rs.Rezervacija.DatumRezervacije,
                    Narucilac = rs.Rezervacija.Narucilac,
                    Stolovi = db.Stol.Where(x=> x.Id == rs.StolId).Select(q=> new RezervacijaPrikaziVM.StolVM
                    {
                        BrojStola = q.Id,
                        BrojMjesta = q.BrojMjesta
                    }).FirstOrDefault()
                }).ToList()
          };

           return View("Prikazi",model);
        }

        public IActionResult DodajForm()
        {
            RezervacijaDodajVM model = this.GenerisiCmbStavke();

            return View("DodajForm", model);
        }
        public IActionResult Obrisi(int id)
        {
            Rezervacija obrisati = db.Rezervacija.SingleOrDefault(r => r.Id == id);
            IEnumerable<RezervacijaStavke> obrisatiStavke = db.RezervacijaStavke.Where(rs => rs.RezervacijaId == id);
            if (obrisati == null)
                return View("Error");

            foreach (RezervacijaStavke rezervacijaStavke in obrisatiStavke)
            {
                db.Remove(rezervacijaStavke);
            }
            db.Remove(obrisati);
            db.SaveChanges();
            TempData["porukaDelete"] = "Uspjesno obrisana rezervacija";

            return Redirect("/Rezervacija/Prikazi");
        }

        public IActionResult DodajSave(RezervacijaDodajVM model)
        {
            Rezervacija r = new Rezervacija();

            r.DatumEvidencije = DateTime.Now;
            r.DatumRezervacije = model.DatumRezervacije;
            r.NarucilacId = model.Narucilac.NarucilacId;

            db.Add(r);
            db.SaveChanges();

            RezervacijaStavke rs = new RezervacijaStavke();

            rs.StolId = model.StolMjesta.Id;
            rs.RezervacijaId = db.Rezervacija.Where(x=> x.Id == r.Id).FirstOrDefault().Id;

            db.Add(rs);
            db.SaveChanges();

            TempData["porukaDodan"] = "Uspjesno dodana rezervacija";
            return Redirect("/Rezervacija/Prikazi");
        }
    }
}

WebApplication1/Areas/ModulAdmin/Views/Rezervacija/Dodaj.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Rezervacija.RezervacijaDodajVM
@{
    ViewData["Title"] = "DodajForm";
}
<style>
    .slidecontainer {
        width: 100%;
    }

    .slider {
        -webkit-appearance: none;
        width: 100%;
        height: 25px;
        background: #d3d3d3;
        outline: none;
        opacity: 0.7;
        -webkit-transition: .2s;
        transition: opacity .2s;
    }

        .slider:hover {
            opacity: 1;
        }

        .slider::-webkit-slider-thumb {
            -webkit-appearance: none;
            appearance: none;
            width: 25px;
            height: 25px;
            background: #4CAF50;
            cursor: pointer;
        }

        .slider::-moz-range-thumb {
            width: 25px;
            height: 25px;
            background: #4CAF50;
            cursor: pointer;
        }
</style>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Dodaj rezervaciju</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form asp-area="ModulAdmin" asp-controller="Rezervacija" asp-action="DodajSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Gost">
                            Gost:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" asp-for="NarucilacIme" class="form-control" readonly>

                        </div>
                    </div>
                    <input type="hidden" asp-for="NarucilacId" />
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="DatumRezervacije">
                            Datum rezervacije:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="DatumRezervacije" type="datetime-local" class="form-control" />

                        </div>

                    </div>

                    <div class="form-group" style="width:auto;">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Naziv">
                            Naziv:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Naziv" class="form-control" />
                            <span asp-validation-for="Naziv"></span>

                        </div>

                    </div>



                    <div class="form-group" style="width:auto;">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="BrojStolova">
                            Broj mjesta:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="range" asp-for="BrojStolova" min="1" max="35" class="slider" id="myRange" oninput="showVal(this.value)" onchange="showVal(this.value)" />
                            <p>Broj mjesta: <span id="demo"></span></p>

                        </div>
                    </div>


                    <input asp-for="RezervacijaId" type="hidden" />
                    <input asp-for="DatumEvidencije" type="hidden" />
                    <div class="form-group">
                        <div class="col-md-9 text-right">
                            <button type="reset" class="btn btn-primary">Resetiraj</button>
                            <button type="submit" class="btn btn-success">Potvrdi</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>

<script>
    var slider = document.getElementById("myRange");
    var output = document.getElementById("demo");
    output.innerHTML = slider.value;

    slider.oninput = function () {
        output.innerHTML = this.value;
    }
    function showVal(newVal) {
        document.getElementById("demo").innerHTML = newVal;
    }
</script>

WebApplication1/Areas/ModulAdmin/Views/Rezervacija/DodajGost.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Rezervacija.RezervacijaFindGostVM
@{
    ViewData["Title"] = "DodajForm";

    int br = 0;
}

<div class="row">
    <div class="x_panel">
        <div class="x_title">
            <h2>Gosti</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>RB</th>
                        <th>Ime i prezime</th>
                        <th>Email</th>
                        <th>Telefon</th>
                        <th>Adresa</th>
                        <th>Grad</th>
                        <th>Akcija</th>
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var n in Model.htmlRows)
                        {
                            <tr>
                                @{
                                    br++;
                                }
                                <td>@br</td>
                                <td>@n.ImePrezime</td>
                                <td>@n.Email</td>
                                <td>@n.Telefon</td>
                                <td>@n.Adresa</td>
                                <td>@n.GradNaziv</td>
                                <td class="text-center">
                                    <a class="btn btn-info btn-xs" asp-controller="Rezervacija" asp-action="Dodaj" asp-route-id="@n.NarucilacId"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>Dodaj rezervaciju</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>

            </table>
        </div>
        <a asp-controller="Narucilac" asp-action="Dodaj" class="btn btn-primary"> Dodaj novog gosta </a>

    </div>

</div>

WebApplication1/Areas/ModulAdmin/Views/Rezervacija/List.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Rezervacija.RezervacijeListVM

@{
    ViewData["Title"] = "Prikazi";
    var porukaDelete = TempData["porukaDelete"] as string;
    int br = 0;
}



@if (porukaDelete != null)
{
    <div class="alert alert-success" role="alert">
        <strong>Rezervacija obrisana</strong> @porukaDelete
    </div>
}

    <div class="row">
        <div class="x_panel">
            <div class="x_title">
                <h2>Naručioci</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>RB</th>
                            <th>Ime gosta</th>
                            <th>Događaj</th>
                            <th>Datum evidencije</th>
                            <th>Datum rezervacije</th>
                            <th>Broj mjesta</th>
                            <th>Obriši</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model.htmlRows)
                        {

                            <tr>
                                @{ br++;}
                                <td>@br</td>
                                <td>@x.ImePrezime</td>
                                <td>@x.Naziv</td>
                                <td>@x.DatumEvidencije</td>
                                <td>@x.DatumRezervacije</td>
                                <td>@x.BrojMjesta</td>
                                <td class="text-center">
                                    <a class="btn btn-info btn-xs" asp-area="ModulAdmin" asp-controller="Rezervacija" asp-action="Uredi" asp-route-id="@x.RezervacijaId"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Uredi</a>
                                    <a class="btn btn-danger btn-xs" OnClick="confirm('Obrisati rezervaciju?')" asp-area="ModulAdmin" asp-controller="Rezervacija" asp-action="Obrisi" asp-route-id="@x.RezervacijaId"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Obriši</a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <a asp-controller="Rezervacija" asp-action="DodajGost" class="btn btn-primary"> Dodaj novu rezervaciju </a>

        </div>

    </div>

WebApplication1/Areas/ModulAdmin/Views/Rezervacija/Uredi.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Rezervacija.RezervacijaDodajVM
@{
    ViewData["Title"] = "Uredi";
}
<style>
    .slidecontainer {
        width: 100%;
    }

    .slider {
        -webkit-appearance: none;
        width: 100%;
        height: 25px;
        background: #d3d3d3;
        outline: none;
        opacity: 0.7;
        -webkit-transition: .2s;
        transition: opacity .2s;
    }

        .slider:hover {
            opacity: 1;
        }

        .slider::-webkit-slider-thumb {
            -webkit-appearance: none;
            appearance: none;
            width: 25px;
            height: 25px;
            background: #4CAF50;
            cursor: pointer;
        }

        .slider::-moz-range-thumb {
            width: 25px;
            height: 25px;
            background: #4CAF50;
            cursor: pointer;
        }
</style>


<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Dodaj rezervaciju</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form asp-area="ModulAdmin" asp-controller="Rezervacija" asp-action="UrediSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Gost">
                            Gost:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input tpye="text" asp-for="NarucilacIme" asp-items="Model.narucilacLista" readonly class="form-control">
                            <span asp-validation-for="NarucilacIme"></span>
                        </div>
                    </div>
                    <input type="hidden" asp-for="NarucilacId" />
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="DatumRezervacije">
                            Datum rezervacije:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="DatumRezervacije" type="datetime-local" class="form-control" />

                        </div>

                    </div>

                    <div class="form-group" style="width:auto;">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Naziv">
                            Naziv:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Naziv" class="form-control" />
                            <span asp-validation-for="Naziv"></span>

                        </div>

                    </div>


                    <div class="form-group" style="width:auto;">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="BrojStolova">
                            Broj mjesta:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="range" asp-for="BrojStolova" min="1" max="35" class="slider" id="myRange" oninput="showVal(this.value)" onchange="showVal(this.value)" />
                            <p>Broj mjesta: <span id="demo"></span></p>

                        </div>
                    </div>

                    <input asp-for="DatumEvidencije" type="hidden" />
                    <input asp-for="RezervacijaId" type="hidden" />
                    <div class="form-group">
                        <div class="col-md-9 text-right">
                            <button type="reset" class="btn btn-primary">Resetiraj</button>
                            <button type="submit" class="btn btn-success">Potvrdi</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    var slider = document.getElementById("myRange");
    var output = document.getElementById("demo");
    output.innerHTML = slider.value;

    slider.oninput = function () {
        output.innerHTML = this.value;
    }
    function showVal(newVal) {
        document.getElementById("demo").innerHTML = newVal;
    }
</script>