WebApplication1/Areas/ModulAdmin/ViewModels/Obavijest/ObavijestDodajVM.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Obavijest
{

    public class ObavijestDodajVM
    {
        public int ObavijestId { get; set; }

        [Required(ErrorMessage = "Naziv je obavezno polje")]
        [RegularExpression("^.{3,}$", ErrorMessage = "Naziv imat više od 3 karaktera")]
        public string Naziv { get; set; }

        [Required(ErrorMessage = "Sadržaj je obavezno polje")]
        [RegularExpression("^.{10,}$", ErrorMessage = "Sadržaj mora imati više od 10 karaktera")]
        public string Sadrzaj { get; set; }
        public DateTime Datum { get; set; }

        [BindRequired]
        public int ZaposlenikId { get; set; }
        public List<SelectListItem> Zaposlenici { get; set; }


    }
}

WebApplication1/Areas/ModulAdmin/ViewModels/Obavijest/ObavijestListVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Obavijest
{
    public class ObavijestListVM
    {

        public List<Row> htmlRows {get;set;}
        public class Row
        {
            public string Naziv { get; set; }
            public string Sadrzaj { get; set; }
            public string ImePrezime { get; set; }
            public DateTime Datum { get; set; }
            public int ObavijestId { get; set; }
        }
    }
}

WebApplication1/Models/Obavijest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Obavijest
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Sadrzaj { get; set; }

        public int ZaposlenikId { get; set; }
        [ForeignKey("ZaposlenikId")]
        public Zaposlenik Zaposlenik { get; set; }
        public DateTime Datum { get; set; }
    }
}

WebApplication1/Areas/ModulAdmin/Controllers/ObavijestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.Areas.ModulAdmin.ViewModels.Obavijest;
using WebApplication1.EF;
using WebApplication1.Models;
using WebApplication1.Helper;

namespace WebApplication1.Areas.ModulAdmin.Controllers
{
    [Autorizacija(zaposlenik: true, korisnik: false)]

    [Area("ModulAdmin")]
    [Route("/ModulAdmin/Obavijest")]
    public class ObavijestController : Controller
    {
        private MyContext _db;
        public ObavijestController(MyContext baza)
        {
            _db = baza;
        }
        

        [Route("/ModulAdmin/Obavijest/")]
        [Route("/ModulAdmin/Obavijest/List")]
        public IActionResult List()
        {
            ObavijestListVM model = new ObavijestListVM
            {
                htmlRows = _db.Obavijest.Select(s => new ObavijestListVM.Row
                {
                    ObavijestId = s.Id,
                    Naziv = s.Naziv,
                    Sadrzaj = s.Sadrzaj,
                    Datum = s.Datum,
                    ImePrezime = s.Zaposlenik.Ime + " " + s.Zaposlenik.Prezime
                }).ToList()
            };         
            return View(model);
        }


        [Route("/AdminModul/Dodaj")]
        public IActionResult Dodaj()
        {
            ObavijestDodajVM model = new ObavijestDodajVM();
            GenerisiCmbStavke(model);
            return View(model);
        }
        [Route("/AdminModul/Obavijest/Obrisi")]
        [HttpGet]
        public IActionResult Obrisi(int id)
        {
            Obavijest obrisi = _db.Obavijest.Find(id);
            _db.Remove(obrisi);
            _db.SaveChanges();
            return RedirectToAction("List");
        }

        [Route("/AdminModul/Obavijest/DodajSave")]
        [HttpPost]
        public IActionResult DodajSave(ObavijestDodajVM model)
        {
            if (ModelState.IsValid)
            {
                Obavijest o = _db.Obavijest.Find(model.ObavijestId);

                if (o == null)
                {
                    o = new Obavijest();
                    _db.Add(o);

                }

                o.Datum = model.Datum;
                o.Naziv = model.Naziv;
                o.Sadrzaj = model.Sadrzaj;
                o.ZaposlenikId = model.ZaposlenikId;

                _db.SaveChanges();
                return RedirectToAction("List");
            }
            else
            {
                GenerisiCmbStavke(model);
                return View("Dodaj",model);

            }
        }

        [Route("/AdminModul/Obavijest/UrediSave")]
        [HttpPost]
        public IActionResult UrediSave(ObavijestDodajVM model)
        {
            if (ModelState.IsValid)
            {
                Obavijest o = _db.Obavijest.Find(model.ObavijestId);

                if (o == null)
                {
                    o = new Obavijest();
                    _db.Add(o);

                }

                o.Datum = model.Datum;
                o.Naziv = model.Naziv;
                o.Sadrzaj = model.Sadrzaj;
                o.ZaposlenikId = model.ZaposlenikId;

                _db.SaveChanges();
                return RedirectToAction("List");
            }
            else
            {
                GenerisiCmbStavke(model);
                return View("Uredi", model);

            }
        }
        private void GenerisiCmbStavke(ObavijestDodajVM model)
        {
            model.Zaposlenici = _db.Zaposlenik.Where(w => w.RadnoMjestoId == 1).Select(s => new SelectListItem
            {
                Text = s.Ime + " " + s.Prezime,
                Value = s.Id.ToString()
            }).ToList();
        }

        [Route("/AdminModul/Obavijest/Uredi")]
        [HttpGet]
        public IActionResult Uredi(int id)
        {
            Obavijest obavijest = _db.Obavijest.Find(id);

            ObavijestDodajVM model = new ObavijestDodajVM
            {
                ObavijestId = id,
                Datum = obavijest.Datum,
                Sadrzaj = obavijest.Sadrzaj,
                ZaposlenikId  = obavijest.ZaposlenikId,
                Naziv = obavijest.Naziv
            };
            GenerisiCmbStavke(model);
            return View(model);
        }

    }
}

WebApplication1/Areas/ModulAdmin/Views/Obavijest/Dodaj.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Obavijest.ObavijestDodajVM
@{ 
    ViewData["Title"] = "Dodaj";
}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Dodaj obavijest</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form asp-area="ModulAdmin" asp-controller="Obavijest" asp-action="DodajSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Naziv">
                            Naziv:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Naziv" class="form-control" />
                            <span asp-validation-for="Naziv"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Sadrzaj">
                            Sadržaj:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea asp-for="Sadrzaj" class="form-control" rows="3" style="resize:none"></textarea>
                            <span asp-validation-for="Sadrzaj"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Datum">
                            Datum :
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Datum" type="datetime-local" class="form-control" id="Datum" />
                            <span asp-validation-for="Datum"></span>

                        </div>
                        </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Zaposlenik">
                            Zaposlenik:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select asp-for="ZaposlenikId" asp-items="Model.Zaposlenici" class="form-control">
                                <option value="" disabled hidden selected>(Odaberi zaposlenika)</option>
                            </select>
                            <span asp-validation-for="ZaposlenikId"></span>
                        </div>
                    </div>

                        <input asp-for="ObavijestId" type="hidden" />

                        <div class="form-group">
                            <div class="col-md-9 text-right">
                                <button type="reset" class="btn btn-primary">Resetiraj</button>
                                <button type="submit" class="btn btn-success">Potvrdi</button>
                            </div>
                        </div>
</form>
            </div>
        </div>
        </div>
    </div>

WebApplication1/Areas/ModulAdmin/Views/Obavijest/List.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Obavijest.ObavijestListVM
@{
    ViewData["Title"] = "Obavijest";
    int br = 0;
}

<div class="row">
    <div class="x_panel">
        <div class="x_title">
            <h2>Obavijesti</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>RB</th>
                        <th>Naziv</th>
                        <th>Sadržaj</th>
                        <th>Datum</th>
                        <th>Objavio</th>
                        <th>Akcija</th>
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var o in Model.htmlRows)
                        {
                            <tr>
                                @{
                                    br++;
                                }
                                <td>@br</td>
                                <td>@o.Naziv</td>
                                <td>@o.Sadrzaj</td>
                                <td>@o.Datum</td>
                                <td>@o.ImePrezime</td>
                                <td class="text-center">
                                    <a class="btn btn-info btn-xs" asp-controller="Obavijest" asp-action="Uredi" asp-route-id="@o.ObavijestId"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Uredi</a>
                                    <a class="btn btn-danger btn-xs" asp-controller="Obavijest" asp-action="Obrisi" asp-route-id="@o.ObavijestId" OnClick="confirm('Obrisati obavijest?')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Obriši</a>
                                </td>

                            </tr>
                        }
                    }
                </tbody>

            </table>
        </div>
        <a asp-controller="Obavijest" asp-action="Dodaj" class="btn btn-primary"> Dodaj novu obavijest </a>
    </div>



</div>

WebApplication1/Areas/ModulAdmin/Views/Obavijest/Uredi.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Obavijest.ObavijestDodajVM
@{
    ViewData["Title"] = "Uredi";
}



<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Dodaj naručioca</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form asp-area="ModulAdmin" asp-controller="Obavijest" asp-action="UrediSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Naziv">
                            Naziv:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Naziv" class="form-control" />
                            <span asp-validation-for="Naziv"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Sadrzaj">
                            Sadržaj:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea asp-for="Sadrzaj" class="form-control" rows="3" style="resize:none"></textarea>
                            <span asp-validation-for="Sadrzaj"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Datum">
                            Datum :
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Datum" type="datetime-local" class="form-control" id="Datum" />
                            <span asp-validation-for="Datum"></span>

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Zaposlenik">
                            Zaposlenik:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select asp-for="ZaposlenikId" asp-items="Model.Zaposlenici" class="form-control">
                                <option value="" disabled hidden selected>(Odaberi zaposlenika)</option>
                            </select>
                            <span asp-validation-for="ZaposlenikId"></span>
                        </div>
                    </div>

                    <input asp-for="ObavijestId" type="hidden" />

                    <div class="form-group">
                        <div class="col-md-9 text-right">
                            <button type="reset" class="btn btn-primary">Resetiraj</button>
                            <button type="submit" class="btn btn-success">Potvrdi</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>